import { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useTranslation } from 'react-i18next';
import {
  Activity,
  AlertCircle,
  Calendar,
  CheckCircle,
  Download,
  Eye,
  FileText,
  Filter,
  FlaskConical,
  Heart,
  Phone,
  Pill,
  Search,
  Shield,
  ShieldCheck,
  Stethoscope,
  Video,
  X,
} from 'lucide-react';
import { Skeleton } from '../../components/Skeleton';
import { usePatientInsurance, type PatientInsuranceActivity } from '../../hooks';
import { useAuth } from '../../lib/auth-context';
import { dateTimeFormatWithNumerals, formatLocaleDigits, resolveLocale } from '../../lib/i18n-ui';

type InsuranceTab = 'claims' | 'preauth' | 'benefits' | 'documents';
type StatusFilter = 'all' | PatientInsuranceActivity['status'];
type DocModalType = 'card' | 'policy' | 'eob' | 'annual' | null;

function statusClasses(status: PatientInsuranceActivity['status']) {
  if (status === 'approved') return 'bg-emerald-50 text-emerald-700 border-emerald-200';
  if (status === 'pending') return 'bg-amber-50 text-amber-700 border-amber-200';
  return 'bg-blue-50 text-blue-700 border-blue-200';
}

export const PatientInsurance = () => {
  const { t, i18n } = useTranslation('common');
  const { user } = useAuth();
  const { data, loading, error } = usePatientInsurance(user?.id);
  const [tab, setTab] = useState<InsuranceTab>('claims');
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [showExclusions, setShowExclusions] = useState(false);
  const [cardDownloaded, setCardDownloaded] = useState(false);
  const [showContactModal, setShowContactModal] = useState(false);
  const [activeDocModal, setActiveDocModal] = useState<DocModalType>(null);

  const uiLang = i18n.language ?? 'en';
  const locale = resolveLocale(uiLang);
  const formatDate = (value: string | null | undefined) =>
    value
      ? new Date(value).toLocaleDateString(
          locale,
          dateTimeFormatWithNumerals(uiLang, {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
          })
        )
      : t('shared.notAvailable', 'N/A');
  const money = (value: number | null | undefined) =>
    value == null ? '—' : `AED ${formatLocaleDigits(Math.round(value), uiLang)}`;

  const primaryPlan = data?.primaryPlan ?? null;
  const coPay = primaryPlan?.coPayPercent ?? null;
  const coveredPercent = coPay == null ? null : Math.max(0, 100 - coPay);
  const annualLimit = primaryPlan?.annualLimit ?? null;
  const annualUsed = primaryPlan?.annualLimitUsed ?? 0;
  const usedPct = annualLimit && annualLimit > 0 ? Math.min(100, (annualUsed / annualLimit) * 100) : 0;

  const activity = useMemo(() => data?.activity ?? [], [data?.activity]);
  const totals = useMemo(
    () =>
      activity.reduce(
        (acc, row) => ({
          total: acc.total + row.totalEstimate,
          covered: acc.covered + row.coveredEstimate,
          patient: acc.patient + row.patientShareEstimate,
          pending: acc.pending + (row.status === 'pending' ? 1 : 0),
        }),
        { total: 0, covered: 0, patient: 0, pending: 0 }
      ),
    [activity]
  );

  const filteredActivity = useMemo(() => {
    const q = search.trim().toLowerCase();
    return activity.filter((row) => {
      const matchesStatus = statusFilter === 'all' || row.status === statusFilter;
      const matchesSearch =
        !q ||
        row.provider.toLowerCase().includes(q) ||
        row.service.toLowerCase().includes(q) ||
        row.referenceCode.toLowerCase().includes(q);
      return matchesStatus && matchesSearch;
    });
  }, [activity, search, statusFilter]);

  const handleDownloadCard = () => {
    const lines = [
      'INSURANCE CARD',
      '==============',
      `Provider:    ${primaryPlan?.providerCompany ?? 'N/A'}`,
      `Plan:        ${primaryPlan?.planName ?? 'N/A'}`,
      `Member Name: ${data?.patientName ?? 'N/A'}`,
      `Member ID:   ${primaryPlan?.memberId ?? primaryPlan?.policyNumber ?? 'N/A'}`,
      `Policy No:   ${primaryPlan?.policyNumber ?? 'N/A'}`,
      `Coverage:    ${coveredPercent == null ? 'N/A' : `${coveredPercent}%`}`,
      `Co-Pay:      ${coPay == null ? 'N/A' : `${coPay}%`}`,
      `Valid Until: ${formatDate(primaryPlan?.validUntil)}`,
      `Annual Limit: ${money(annualLimit)}`,
      '',
      'Generated by CeenAiX Health Platform',
    ];
    const text = lines.join('\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `insurance-card-${primaryPlan?.policyNumber ?? 'card'}.txt`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
    setCardDownloaded(true);
    setTimeout(() => setCardDownloaded(false), 3000);
  };

  const downloadTextFile = (filename: string, content: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPolicy = () => {
    const lines = [
      'POLICY DOCUMENT',
      '===============',
      `Provider:     ${primaryPlan?.providerCompany ?? 'N/A'}`,
      `Plan:         ${primaryPlan?.planName ?? 'N/A'}`,
      `Policy No:    ${primaryPlan?.policyNumber ?? 'N/A'}`,
      `Member ID:    ${primaryPlan?.memberId ?? 'N/A'}`,
      `Coverage:     ${coveredPercent == null ? 'N/A' : `${coveredPercent}%`}`,
      `Co-Pay:       ${coPay == null ? 'N/A' : `${coPay}%`}`,
      `Valid Until:  ${formatDate(primaryPlan?.validUntil)}`,
      `Annual Limit: ${money(annualLimit)}`,
      '',
      'Generated by CeenAiX Health Platform',
    ];
    downloadTextFile(`policy-${primaryPlan?.policyNumber ?? 'document'}.txt`, lines.join('\n'));
  };

  const handleDownloadEob = () => {
    const lines = [
      'EXPLANATION OF BENEFITS (EOB)',
      '=============================',
      `Member: ${data?.patientName ?? 'N/A'}`,
      `Plan:   ${primaryPlan?.planName ?? 'N/A'}`,
      '',
      'CLAIMS ACTIVITY',
      '---------------',
    ];
    for (const row of activity) {
      lines.push(`${formatDate(row.date)} | ${row.service} | ${row.provider}`);
      lines.push(`  Full: ${money(row.totalEstimate)} | Covered: ${money(row.coveredEstimate)} | You paid: ${money(row.patientShareEstimate)}`);
      lines.push(`  Status: ${row.status} | Ref: ${row.referenceCode}`);
      lines.push('');
    }
    lines.push(`TOTAL COVERED: ${money(totals.covered)}`);
    lines.push(`TOTAL YOU PAID: ${money(totals.patient)}`);
    lines.push('');
    lines.push('Generated by CeenAiX Health Platform');
    downloadTextFile('explanation-of-benefits.txt', lines.join('\n'));
  };

  const handleDownloadAnnual = () => {
    const lines = [
      'ANNUAL INSURANCE SUMMARY',
      '========================',
      `Member:       ${data?.patientName ?? 'N/A'}`,
      `Provider:     ${primaryPlan?.providerCompany ?? 'N/A'}`,
      `Plan:         ${primaryPlan?.planName ?? 'N/A'}`,
      '',
      'ANNUAL USAGE',
      '------------',
      `Annual Limit:  ${money(annualLimit)}`,
      `Amount Used:   ${money(annualUsed)}`,
      `Remaining:     ${money((annualLimit ?? 0) - annualUsed)}`,
      `Usage:         ${Math.round(usedPct)}%`,
      '',
      `Total Claims:  ${activity.length}`,
      `Pending:       ${totals.pending}`,
      '',
      'Generated by CeenAiX Health Platform',
    ];
    downloadTextFile('annual-summary.txt', lines.join('\n'));
  };

  const handleContactInsurer = () => {
    setShowContactModal(true);
  };

  const closeContactModal = () => {
    setShowContactModal(false);
  };

  const tabs: Array<{ key: InsuranceTab; label: string; badge?: number }> = [
    { key: 'claims', label: t('patient.insurance.tabClaims'), badge: activity.length },
    { key: 'preauth', label: t('patient.insurance.tabPreauth') },
    { key: 'benefits', label: t('patient.insurance.tabBenefits') },
    { key: 'documents', label: t('patient.insurance.tabDocuments') },
  ];

  const benefits = [
    {
      icon: Stethoscope,
      color: 'text-teal-600',
      bg: 'bg-teal-100',
      name: t('patient.insurance.benefitSpecialists'),
      pct: coveredPercent == null ? '—' : `${formatLocaleDigits(coveredPercent, uiLang)}%`,
      copay: coPay == null ? t('patient.insurance.planNeeded') : t('patient.insurance.coPayPct', { percent: formatLocaleDigits(coPay, uiLang) }),
      notes: t('patient.insurance.benefitSpecialistsNote'),
    },
    {
      icon: FlaskConical,
      color: 'text-indigo-600',
      bg: 'bg-indigo-100',
      name: t('patient.insurance.benefitLabs'),
      pct: coveredPercent == null ? '—' : `${formatLocaleDigits(coveredPercent, uiLang)}%`,
      copay: coPay == null ? t('patient.insurance.planNeeded') : t('patient.insurance.coPayPct', { percent: formatLocaleDigits(coPay, uiLang) }),
      notes: t('patient.insurance.benefitLabsNote'),
    },
    {
      icon: Pill,
      color: 'text-violet-600',
      bg: 'bg-violet-100',
      name: t('patient.insurance.benefitPharmacy'),
      pct: coveredPercent == null ? '—' : `${formatLocaleDigits(Math.max(0, coveredPercent - 10), uiLang)}%`,
      copay: coPay == null ? t('patient.insurance.planNeeded') : t('patient.insurance.pharmacyCoPayNote'),
      notes: t('patient.insurance.benefitPharmacyNote'),
    },
    {
      icon: Video,
      color: 'text-blue-600',
      bg: 'bg-blue-100',
      name: t('patient.insurance.benefitTelehealth'),
      pct: coveredPercent == null ? '—' : `${formatLocaleDigits(coveredPercent, uiLang)}%`,
      copay: coPay == null ? t('patient.insurance.planNeeded') : t('patient.insurance.coPayPct', { percent: formatLocaleDigits(coPay, uiLang) }),
      notes: t('patient.insurance.benefitTelehealthNote'),
    },
    {
      icon: Heart,
      color: 'text-emerald-600',
      bg: 'bg-emerald-100',
      name: t('patient.insurance.benefitPreventive'),
      pct: primaryPlan ? '100%' : '—',
      copay: primaryPlan ? t('patient.insurance.noCopay') : t('patient.insurance.planNeeded'),
      notes: t('patient.insurance.benefitPreventiveNote'),
    },
    {
      icon: Activity,
      color: 'text-amber-600',
      bg: 'bg-amber-100',
      name: t('patient.insurance.benefitPhysio'),
      pct: coveredPercent == null ? '—' : `${formatLocaleDigits(Math.max(0, coveredPercent - 10), uiLang)}%`,
      copay: coPay == null ? t('patient.insurance.planNeeded') : t('patient.insurance.referralRequired'),
      notes: t('patient.insurance.benefitPhysioNote'),
    },
  ];

  // ── Doc Modal renderer ─────────────────────────────────────────────────────
  const renderDocModal = () => {
    if (!activeDocModal) return null;

    let title = '';
    let content: React.ReactNode = null;
    let onDownload: (() => void) | null = null;

    if (activeDocModal === 'card') {
      title = t('patient.insurance.docCard');
      onDownload = handleDownloadCard;
      content = (
        <div className="space-y-3">
          <div
            className="relative overflow-hidden rounded-2xl p-6"
            style={{ background: 'linear-gradient(135deg, #1E3A5F 0%, #1D4ED8 100%)' }}
          >
            <div className="absolute -bottom-6 -right-6 h-32 w-32 rounded-full bg-white/10" />
            <div className="mb-4 text-sm font-bold text-white">{primaryPlan?.providerCompany ?? '—'}</div>
            <div className="mb-1 font-mono text-base font-bold uppercase tracking-widest text-white">
              {data?.patientName ?? '—'}
            </div>
            <div className="mb-4 font-mono text-xs text-white/70">
              Member: {primaryPlan?.memberId ?? primaryPlan?.policyNumber ?? '—'}
            </div>
            <div className="flex items-end justify-between text-xs text-white/70">
              <div>
                <div>Valid Until</div>
                <div className="font-mono font-bold text-white">{formatDate(primaryPlan?.validUntil)}</div>
              </div>
              <div className="text-right">
                <div>Co-Pay</div>
                <div className="font-mono font-bold text-white">
                  {coPay == null ? '—' : `${coPay}%`}
                </div>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Plan', value: primaryPlan?.planName ?? '—' },
              { label: 'Policy No', value: primaryPlan?.policyNumber ?? '—' },
              { label: 'Coverage', value: coveredPercent == null ? '—' : `${coveredPercent}%` },
              { label: 'Annual Limit', value: money(annualLimit) },
            ].map((row) => (
              <div key={row.label} className="rounded-xl bg-slate-50 p-3">
                <div className="text-xs text-slate-400">{row.label}</div>
                <div className="mt-0.5 font-mono text-sm font-bold text-slate-900">{row.value}</div>
              </div>
            ))}
          </div>
        </div>
      );
    }

    if (activeDocModal === 'policy') {
      title = t('patient.insurance.docPolicy');
      onDownload = handleDownloadPolicy;
      content = (
        <div className="space-y-3">
          <div className="rounded-xl bg-slate-50 p-4">
            <h4 className="mb-3 text-sm font-bold text-slate-700">Policy Information</h4>
            <div className="space-y-2">
              {[
                { label: 'Provider', value: primaryPlan?.providerCompany ?? '—' },
                { label: 'Plan Name', value: primaryPlan?.planName ?? '—' },
                { label: 'Policy Number', value: primaryPlan?.policyNumber ?? '—' },
                { label: 'Member ID', value: primaryPlan?.memberId ?? '—' },
                { label: 'Coverage Type', value: primaryPlan?.coverageType ?? '—' },
                { label: 'Valid Until', value: formatDate(primaryPlan?.validUntil) },
              ].map((row) => (
                <div key={row.label} className="flex items-center justify-between border-b border-slate-100 pb-2 last:border-0">
                  <span className="text-sm text-slate-500">{row.label}</span>
                  <span className="font-mono text-sm font-bold text-slate-900">{row.value}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="rounded-xl bg-slate-50 p-4">
            <h4 className="mb-3 text-sm font-bold text-slate-700">Coverage Details</h4>
            <div className="space-y-2">
              {[
                { label: 'Coverage', value: coveredPercent == null ? '—' : `${coveredPercent}%` },
                { label: 'Co-Pay', value: coPay == null ? '—' : `${coPay}%` },
                { label: 'Annual Limit', value: money(annualLimit) },
                { label: 'Used This Year', value: money(annualUsed) },
              ].map((row) => (
                <div key={row.label} className="flex items-center justify-between border-b border-slate-100 pb-2 last:border-0">
                  <span className="text-sm text-slate-500">{row.label}</span>
                  <span className="font-mono text-sm font-bold text-slate-900">{row.value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      );
    }

    if (activeDocModal === 'eob') {
      title = 'Explanation of Benefits';
      onDownload = handleDownloadEob;
      content = (
        <div className="space-y-3">
          <div className="grid grid-cols-3 gap-3">
            <div className="rounded-xl bg-slate-50 p-3 text-center">
              <div className="text-xs text-slate-400">Total</div>
              <div className="mt-1 font-mono text-sm font-bold text-slate-900">{money(totals.total)}</div>
            </div>
            <div className="rounded-xl bg-emerald-50 p-3 text-center">
              <div className="text-xs text-emerald-600">Covered</div>
              <div className="mt-1 font-mono text-sm font-bold text-emerald-700">{money(totals.covered)}</div>
            </div>
            <div className="rounded-xl bg-blue-50 p-3 text-center">
              <div className="text-xs text-blue-600">You Paid</div>
              <div className="mt-1 font-mono text-sm font-bold text-blue-700">{money(totals.patient)}</div>
            </div>
          </div>
          <div className="space-y-2">
            {activity.length === 0 ? (
              <div className="rounded-xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-400">
                No claims activity found
              </div>
            ) : (
              activity.map((row) => (
                <div key={row.id} className="rounded-xl border border-slate-100 bg-white p-4">
                  <div className="mb-2 flex items-center justify-between">
                    <span className="text-sm font-bold text-slate-900">{row.service}</span>
                    <span className={`rounded-full border px-2 py-0.5 text-xs font-bold ${statusClasses(row.status)}`}>
                      {row.status}
                    </span>
                  </div>
                  <div className="text-xs text-slate-500">{row.provider} · {formatDate(row.date)}</div>
                  <div className="mt-2 grid grid-cols-3 gap-2 text-center">
                    <div>
                      <div className="text-xs text-slate-400">Full</div>
                      <div className="font-mono text-xs font-bold text-slate-700">{money(row.totalEstimate)}</div>
                    </div>
                    <div>
                      <div className="text-xs text-emerald-600">Covered</div>
                      <div className="font-mono text-xs font-bold text-emerald-700">{money(row.coveredEstimate)}</div>
                    </div>
                    <div>
                      <div className="text-xs text-blue-600">You Paid</div>
                      <div className="font-mono text-xs font-bold text-blue-700">{money(row.patientShareEstimate)}</div>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      );
    }

    if (activeDocModal === 'annual') {
      title = 'Annual Summary';
      onDownload = handleDownloadAnnual;
      content = (
        <div className="space-y-3">
          <div className="rounded-xl bg-gradient-to-r from-teal-50 to-blue-50 p-5">
            <h4 className="mb-3 text-sm font-bold text-slate-700">Annual Usage</h4>
            <div className="mb-3">
              <div className="mb-1 flex justify-between text-sm">
                <span className="text-slate-600">Used</span>
                <span className="font-bold text-slate-900">{money(annualUsed)} / {money(annualLimit)}</span>
              </div>
              <div className="h-3 overflow-hidden rounded-full bg-white">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-teal-500 to-blue-500 transition-all duration-700"
                  style={{ width: `${usedPct}%` }}
                />
              </div>
              <div className="mt-1 text-right text-xs text-slate-400">{Math.round(usedPct)}% used</div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Annual Limit', value: money(annualLimit), color: 'text-blue-600', bg: 'bg-blue-50' },
              { label: 'Amount Used', value: money(annualUsed), color: 'text-violet-600', bg: 'bg-violet-50' },
              { label: 'Remaining', value: money((annualLimit ?? 0) - annualUsed), color: 'text-emerald-600', bg: 'bg-emerald-50' },
              { label: 'Total Claims', value: String(activity.length), color: 'text-slate-700', bg: 'bg-slate-50' },
            ].map((row) => (
              <div key={row.label} className={`rounded-xl p-4 ${row.bg}`}>
                <div className="text-xs text-slate-500">{row.label}</div>
                <div className={`mt-1 font-mono text-lg font-bold ${row.color}`}>{row.value}</div>
              </div>
            ))}
          </div>
          <div className="rounded-xl bg-slate-50 p-4">
            <h4 className="mb-2 text-sm font-bold text-slate-700">Plan Details</h4>
            <div className="space-y-2">
              {[
                { label: 'Provider', value: primaryPlan?.providerCompany ?? '—' },
                { label: 'Plan', value: primaryPlan?.planName ?? '—' },
                { label: 'Coverage', value: coveredPercent == null ? '—' : `${coveredPercent}%` },
                { label: 'Pending Claims', value: String(totals.pending) },
              ].map((row) => (
                <div key={row.label} className="flex items-center justify-between border-b border-slate-100 pb-2 last:border-0">
                  <span className="text-sm text-slate-500">{row.label}</span>
                  <span className="font-mono text-sm font-bold text-slate-900">{row.value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      );
    }

    return createPortal(
      <div
        className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 p-4"
        onClick={() => setActiveDocModal(null)}
      >
        <div
          className="relative flex max-h-[85vh] w-full max-w-lg flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex flex-shrink-0 items-center justify-between border-b border-slate-100 px-6 py-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50">
                <FileText className="h-5 w-5 text-blue-600" />
              </div>
              <div>
                <h2 className="font-bold text-slate-900">{title}</h2>
                <p className="text-xs text-slate-400">{primaryPlan?.planName ?? '—'}</p>
              </div>
            </div>
            <button
              type="button"
              onClick={() => setActiveDocModal(null)}
              className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-100"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6">
            {content}
          </div>

          {/* Footer */}
          <div className="flex flex-shrink-0 items-center justify-end gap-2 border-t border-slate-100 px-6 py-4">
            {onDownload ? (
              <button
                type="button"
                onClick={() => { onDownload?.(); }}
                className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-teal-700"
              >
                <Download className="h-4 w-4" />
                Download
              </button>
            ) : null}
            <button
              type="button"
              onClick={() => setActiveDocModal(null)}
              className="rounded-lg border-2 border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
            >
              Close
            </button>
          </div>
        </div>
      </div>,
      document.body
    );
  };

  if (loading) {
    return (
      <div className="space-y-5">
        <Skeleton className="h-20 rounded-2xl" />
        <Skeleton className="h-72 rounded-2xl" />
        <Skeleton className="h-80 rounded-2xl" />
      </div>
    );
  }

  return (
    <div className="animate-fadeIn space-y-5">
      {error ? (
        <div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">
          {t('patient.insurance.loadError')}
        </div>
      ) : null}

      <div className="flex flex-wrap items-center gap-4 rounded-2xl border border-slate-200 bg-white px-6 py-4 shadow-sm">
        <div className="flex flex-1 items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-100">
            <Shield className="h-5 w-5 text-blue-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-slate-900">{t('patient.insurance.title')}</h1>
            <p className="text-xs text-slate-400">{t('patient.insurance.subtitle')}</p>
          </div>
        </div>
        <button
          type="button"
          onClick={handleDownloadCard}
          className={`flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors ${
            cardDownloaded
              ? 'bg-emerald-100 text-emerald-700'
              : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
          }`}
        >
          <Download className="h-4 w-4" />
          {cardDownloaded ? '✓ Downloaded!' : t('patient.insurance.downloadCard')}
        </button>
        <button
          type="button"
          onClick={handleContactInsurer}
          className="flex items-center gap-2 rounded-xl bg-blue-50 px-4 py-2 text-sm font-medium text-blue-700 transition-colors hover:bg-blue-100"
        >
          <Phone className="h-4 w-4" /> {primaryPlan?.providerCompany ?? t('patient.insurance.contactInsurer')}
        </button>
      </div>

      <div className="rounded-2xl border border-slate-100 bg-white p-8 shadow-sm">
        <div className="flex flex-col items-center">
          <div
            className="relative min-h-[200px] w-full max-w-lg overflow-hidden rounded-2xl p-6"
            style={{
              background: 'linear-gradient(135deg, #1E3A5F 0%, #1D4ED8 100%)',
              boxShadow: '0 20px 60px rgba(30,58,95,0.35)',
            }}
          >
            <div className="absolute -bottom-8 -right-8 h-40 w-40 rounded-full bg-white/10" />
            <div className="absolute -bottom-4 -right-4 h-24 w-24 rounded-full bg-white/10" />

            <div className="relative mb-5 flex items-start justify-between">
              <span className="text-sm font-bold text-white">
                {primaryPlan?.providerCompany ?? t('patient.insurance.noInsuranceProvider')}
              </span>
              <div className="flex items-center gap-2">
                <span className="rounded-full bg-emerald-400/20 px-2 py-0.5 text-[10px] font-bold text-emerald-200">
                  {primaryPlan?.isActive ? t('patient.insurance.activeBadge') : t('patient.insurance.notLinkedBadge')}
                </span>
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-white/20 text-sm font-bold text-white">
                  {primaryPlan?.providerCompany?.charAt(0).toUpperCase() ?? 'C'}
                </div>
              </div>
            </div>

            <div className="relative mb-3">
              <div className="mb-1 font-mono text-base font-bold uppercase tracking-widest text-white">
                {data?.patientName ?? t('patient.insurance.memberNameMissing')}
              </div>
              <div className="font-mono text-xs text-white/70">
                {t('patient.insurance.member')}: {primaryPlan?.memberId ?? primaryPlan?.policyNumber ?? '—'}
              </div>
            </div>

            <div className="relative mb-5 flex flex-wrap items-center gap-3">
              <span className="text-base font-bold text-amber-300">{primaryPlan?.planName ?? t('patient.insurance.noPlan')}</span>
              <span className="text-sm text-white/60">{primaryPlan?.coverageType ?? t('patient.insurance.coverageNotRecorded')}</span>
            </div>

            <div className="relative flex items-end justify-between text-xs text-white/70">
              <div>
                <div>{t('patient.insurance.validUntil')}</div>
                <div className="font-mono font-bold text-white">{formatDate(primaryPlan?.validUntil)}</div>
              </div>
              <div className="text-right">
                <div>{t('patient.insurance.copay')}</div>
                <div className="font-mono font-bold text-white">
                  {coPay == null ? '—' : `${formatLocaleDigits(coPay, uiLang)}%`}
                </div>
              </div>
            </div>
          </div>

          <div className="mt-8 grid w-full gap-4 md:grid-cols-4">
            <div className="rounded-xl bg-emerald-50 p-5 text-center">
              <div className="mb-1 text-3xl font-bold text-emerald-600">
                {coveredPercent == null ? '—' : `${formatLocaleDigits(coveredPercent, uiLang)}%`}
              </div>
              <div className="text-sm text-slate-600">{t('patient.insurance.coverage')}</div>
            </div>
            <div className="rounded-xl bg-blue-50 p-5 text-center">
              <div className="mb-1 text-3xl font-bold text-blue-600">{money(annualLimit)}</div>
              <div className="text-sm text-slate-600">{t('patient.insurance.annualLimit')}</div>
            </div>
            <div className="rounded-xl bg-violet-50 p-5 text-center">
              <div className="mb-1 text-3xl font-bold text-violet-600">{money(annualUsed)}</div>
              <div className="text-sm text-slate-600">{t('patient.insurance.usedThisYear')}</div>
            </div>
            <div className="rounded-xl bg-amber-50 p-5 text-center">
              <div className="mb-1 text-3xl font-bold text-amber-600">{formatLocaleDigits(totals.pending, uiLang)}</div>
              <div className="text-sm text-slate-600">{t('patient.insurance.pendingActivity')}</div>
            </div>
          </div>

          <div className="mt-6 w-full max-w-3xl">
            <div className="mb-2 flex justify-between text-sm">
              <span className="text-slate-600">{t('patient.insurance.annualUsage')}</span>
              <span className="font-bold text-slate-900">
                {money(annualUsed)} / {money(annualLimit)}
              </span>
            </div>
            <div className="h-3 overflow-hidden rounded-full bg-slate-100">
              <div
                className="h-full rounded-full bg-gradient-to-r from-teal-500 to-blue-500 transition-all duration-700"
                style={{ width: `${usedPct}%` }}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="overflow-hidden rounded-2xl bg-white shadow-sm">
        <div className="border-b border-slate-100 px-4 sm:px-6">
          <div className="flex min-w-max gap-6 overflow-x-auto sm:gap-8">
            {tabs.map((item) => {
              const active = tab === item.key;
              return (
                <button
                  key={item.key}
                  type="button"
                  onClick={() => setTab(item.key)}
                  className={`relative px-2 py-4 text-[15px] font-medium transition-all duration-300 ${
                    active ? 'text-blue-600' : 'text-slate-400 hover:text-slate-600'
                  }`}
                >
                  {item.label}
                  {typeof item.badge === 'number' ? (
                    <span className="ml-2 rounded-full bg-blue-100 px-2 py-0.5 text-xs font-bold text-blue-700">
                      {formatLocaleDigits(item.badge, uiLang)}
                    </span>
                  ) : null}
                  {active ? <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-600" /> : null}
                </button>
              );
            })}
          </div>
        </div>

        <div className="p-6">
          {tab === 'claims' ? (
            <div className="space-y-5">
              <div className="grid gap-4 md:grid-cols-3">
                <div className="rounded-xl bg-slate-50 p-5">
                  <div className="text-xs uppercase tracking-wide text-slate-400">{t('patient.insurance.totalActivity')}</div>
                  <div className="mt-1 font-mono text-2xl font-bold text-slate-900">{money(totals.total)}</div>
                </div>
                <div className="rounded-xl bg-emerald-50 p-5">
                  <div className="text-xs uppercase tracking-wide text-emerald-600">{t('patient.insurance.planCovered')}</div>
                  <div className="mt-1 font-mono text-2xl font-bold text-emerald-700">{money(totals.covered)}</div>
                </div>
                <div className="rounded-xl bg-blue-50 p-5">
                  <div className="text-xs uppercase tracking-wide text-blue-600">{t('patient.insurance.youPaid')}</div>
                  <div className="mt-1 font-mono text-2xl font-bold text-blue-700">{money(totals.patient)}</div>
                </div>
              </div>

              <div className="flex flex-col gap-3 md:flex-row">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                  <input
                    value={search}
                    onChange={(event) => setSearch(event.target.value)}
                    placeholder={t('patient.insurance.searchActivity')}
                    className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-4 text-sm outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
                  />
                </div>
                <div className="relative">
                  <Filter className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                  <select
                    value={statusFilter}
                    onChange={(event) => setStatusFilter(event.target.value as StatusFilter)}
                    className="rounded-xl border border-slate-200 py-3 pl-10 pr-8 text-sm outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
                  >
                    <option value="all">{t('patient.insurance.filterAll')}</option>
                    <option value="approved">{t('patient.insurance.statusApproved')}</option>
                    <option value="pending">{t('patient.insurance.statusPending')}</option>
                    <option value="review">{t('patient.insurance.statusReview')}</option>
                  </select>
                </div>
              </div>

              <div className="space-y-3">
                {filteredActivity.length === 0 ? (
                  <div className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">
                    {t('patient.insurance.noActivity')}
                  </div>
                ) : (
                  filteredActivity.map((item) => (
                    <div key={item.id} className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm">
                      <div className="flex flex-wrap items-start justify-between gap-4">
                        <div>
                          <div className="flex flex-wrap items-center gap-2">
                            <h3 className="text-base font-bold text-slate-900">{item.service}</h3>
                            <span className={`rounded-full border px-2.5 py-0.5 text-xs font-bold ${statusClasses(item.status)}`}>
                              {t(`patient.insurance.status.${item.status}`)}
                            </span>
                          </div>
                          <div className="mt-1 text-sm text-slate-500">
                            {item.provider} · {item.serviceType} · {formatDate(item.date)}
                          </div>
                          <div className="mt-2 font-mono text-xs text-slate-400">{item.referenceCode}</div>
                        </div>
                        <div className="grid min-w-[260px] grid-cols-3 gap-3 text-right">
                          <div>
                            <div className="text-xs text-slate-400">{t('patient.insurance.fullPrice')}</div>
                            <div className="font-mono font-bold text-slate-900">{money(item.totalEstimate)}</div>
                          </div>
                          <div>
                            <div className="text-xs text-emerald-600">{t('patient.insurance.covered')}</div>
                            <div className="font-mono font-bold text-emerald-700">{money(item.coveredEstimate)}</div>
                          </div>
                          <div>
                            <div className="text-xs text-blue-600">{t('patient.insurance.patientShare')}</div>
                            <div className="font-mono font-bold text-blue-700">{money(item.patientShareEstimate)}</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          ) : null}

          {tab === 'preauth' ? (
            <div className="space-y-4">
              <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6">
                <div className="mb-2 flex items-center gap-2 text-lg font-bold text-slate-900">
                  <AlertCircle className="h-5 w-5 text-amber-600" />
                  {t('patient.insurance.preauthTitle')}
                </div>
                <p className="text-sm text-slate-600">{t('patient.insurance.preauthBody')}</p>
              </div>
              {['MRI / CT imaging', 'High-cost branded medication', 'Elective procedures'].map((label) => (
                <div key={label} className="flex flex-wrap items-center justify-between gap-4 rounded-xl bg-white p-5 shadow-sm">
                  <div className="flex items-center gap-3">
                    <Calendar className="h-5 w-5 text-blue-600" />
                    <div>
                      <div className="font-bold text-slate-900">{label}</div>
                      <div className="text-sm text-slate-500">{primaryPlan?.planName ?? t('patient.insurance.noPlan')}</div>
                    </div>
                  </div>
                  <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">
                    {t('patient.insurance.ruleBased')}
                  </span>
                </div>
              ))}
            </div>
          ) : null}

          {tab === 'benefits' ? (
            <div className="grid gap-4 md:grid-cols-2">
              {benefits.map((benefit) => {
                const Icon = benefit.icon;
                return (
                  <div key={benefit.name} className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm">
                    <div className="mb-3 flex items-start gap-4">
                      <div className={`flex h-12 w-12 items-center justify-center rounded-xl ${benefit.bg}`}>
                        <Icon className={`h-6 w-6 ${benefit.color}`} />
                      </div>
                      <div className="flex-1">
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <h3 className="font-bold text-slate-900">{benefit.name}</h3>
                          <span className="font-mono text-xl font-bold text-teal-600">{benefit.pct}</span>
                        </div>
                        <div className="mt-1 text-sm font-medium text-slate-600">{benefit.copay}</div>
                      </div>
                    </div>
                    <p className="text-sm text-slate-500">{benefit.notes}</p>
                  </div>
                );
              })}
              <button
                type="button"
                onClick={() => setShowExclusions((prev) => !prev)}
                className="rounded-xl border border-slate-200 p-5 text-left transition hover:bg-slate-50 md:col-span-2"
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-slate-900">{t('patient.insurance.exclusionsTitle')}</span>
                  <span className="text-slate-400">{showExclusions ? '▲' : '▼'}</span>
                </div>
                {showExclusions ? <p className="mt-3 text-sm text-slate-500">{t('patient.insurance.exclusionsBody')}</p> : null}
              </button>
            </div>
          ) : null}

          {tab === 'documents' ? (
            <div className="grid gap-4 md:grid-cols-2">
              {[
                {
                  title: t('patient.insurance.docCard'),
                  body: primaryPlan?.cardPhotoUrl ? t('patient.insurance.docCardUploaded') : t('patient.insurance.docCardMissing'),
                  icon: ShieldCheck,
                  action: t('patient.insurance.viewDocument'),
                  modalKey: 'card' as DocModalType,
                },
                {
                  title: t('patient.insurance.docPolicy'),
                  body: primaryPlan?.policyNumber ?? t('patient.insurance.policyMissing'),
                  icon: FileText,
                  action: t('patient.insurance.viewDocument'),
                  modalKey: 'policy' as DocModalType,
                },
                {
                  title: t('patient.insurance.docEob'),
                  body: t('patient.insurance.docEobBody', { count: formatLocaleDigits(activity.length, uiLang) }),
                  icon: CheckCircle,
                  action: t('patient.insurance.generateFromActivity'),
                  modalKey: 'eob' as DocModalType,
                },
                {
                  title: t('patient.insurance.docAnnual'),
                  body: `${money(annualUsed)} ${t('patient.insurance.usedThisYear').toLowerCase()}`,
                  icon: Activity,
                  action: t('patient.insurance.viewSummary'),
                  modalKey: 'annual' as DocModalType,
                },
              ].map((doc) => {
                const Icon = doc.icon;
                return (
                  <div key={doc.title} className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm">
                    <div className="mb-4 flex items-start gap-3">
                      <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50">
                        <Icon className="h-6 w-6 text-blue-600" />
                      </div>
                      <div>
                        <h3 className="font-bold text-slate-900">{doc.title}</h3>
                        <p className="mt-1 text-sm text-slate-500">{doc.body}</p>
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => setActiveDocModal(doc.modalKey)}
                      className="inline-flex items-center gap-2 rounded-lg bg-blue-50 px-3 py-2 text-sm font-medium text-blue-700 transition hover:bg-blue-100"
                    >
                      <Eye className="h-4 w-4" />
                      {doc.action}
                    </button>
                  </div>
                );
              })}
            </div>
          ) : null}
        </div>
      </div>

      <div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-700">
        {t('patient.insurance.dataNote')}
      </div>

      {/* Document Preview Modals */}
      {renderDocModal()}

      {/* Contact Modal */}
      {showContactModal ? createPortal(
        <div
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 p-4"
          onClick={closeContactModal}
        >
          <div
            className="relative w-full max-w-sm rounded-2xl bg-white p-6 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-100">
                  <Phone className="h-5 w-5 text-blue-600" />
                </div>
                <div>
                  <h3 className="font-bold text-slate-900">Contact Insurer</h3>
                  <p className="text-xs text-slate-400">{primaryPlan?.providerCompany ?? 'Insurance Provider'}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={closeContactModal}
                className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-100"
              >
                ✕
              </button>
            </div>

            <div className="space-y-3">
              <a
                href="tel:80032626"
                className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 transition hover:bg-slate-50"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100">
                  <Phone className="h-5 w-5 text-emerald-600" />
                </div>
                <div>
                  <p className="text-sm font-bold text-slate-900">Call Customer Service</p>
                  <p className="text-xs text-slate-500">800-DAMAN (800-32626)</p>
                </div>
              </a>

              <a
                href="https://wa.me/97180032626"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 transition hover:bg-slate-50"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100">
                  <svg viewBox="0 0 24 24" className="h-5 w-5" fill="#25D366">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-bold text-slate-900">WhatsApp</p>
                  <p className="text-xs text-slate-500">Chat with support</p>
                </div>
              </a>

              <a
                href="mailto:members@damanhealth.ae"
                className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 transition hover:bg-slate-50"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100">
                  <FileText className="h-5 w-5 text-blue-600" />
                </div>
                <div>
                  <p className="text-sm font-bold text-slate-900">Email Support</p>
                  <p className="text-xs text-slate-500">members@damanhealth.ae</p>
                </div>
              </a>
            </div>

            <p className="mt-4 text-center text-xs text-slate-400">
              Available Sunday – Thursday, 8:00 AM – 8:00 PM
            </p>
          </div>
        </div>,
        document.body
      ) : null}
    </div>
  );
};